### ISSUE TITLE
Layer is trying to send metrics to dd-agent on localhost

### ISSUE THREAD

**Issue by mbelang** [DataDog/datadog-lambda-layer-python#32]
## Expected Behavior
I should not see a ddtrace error log trying to send metrics to localhost.

## Actual Behavior
Since I updated to 0.10.0, I get that log all the time: ```Failed to send traces to Datadog Agent at http://localhost:8126: [Errno 97] Address family not supported by protocol
```

## Specifications

  - Datadog Lambda Layer version: 0.10.0
  - Python version: 3.7

**Comment by tianchu** [comment]
Hi @mbelang, thanks for the report. Unfortunately I cannot reproduce the issue in my testing lambda with python 3.7 and datadog-lambda 0.10.0. Do you mind providing a code snippet? BTW, are you using the datadog tracer `ddtrace` in your lambda? I believe that's what that log message is suggesting - the tracer is trying to sending traces to the agent, which doesn't exist.

**Comment by mbelang** [comment]
@tianchu you are right. I was prototyping to try to get it working without installing the layer per say. We are installing `datatog-lambda` like a library and I forgot to do to decorate my handler with the `from datadog_lambda.wrapper import datadog_lambda_wrapper` wrapper :)

Thank you. Now it works perfectly

**Comment by mbelang** [comment]
@tianchu we have to do this in our lambda because datadog-lambda doesn't path enough libraries (we are loosing part of traces otherwise) but the problem is that `ddtrace` tries to contact datadog agent. Any idea how we could solve that?

```python
from ddtrace import patch_all as dd_patch_all

dd_patch_all()
```
thanks

**Comment by tianchu** [comment]
Hi @mbelang the work to support the Datadog tracer (`ddtrace`) in the Lambda environment is still underway. Meanwhile, you can patch the X-Ray tracer and rely on the Datadog X-Ray integration to ingest the traces to Datadog. You can find instructions and more details on the integration [here](https://docs.datadoghq.com/integrations/amazon_xray/?tab=python#installing-the-x-ray-client-libraries).

**Comment by mbelang** [comment]
This is what I'm doing and it seems to work well without the ddtrace patcher and only xray. Thx for the update.
