### ISSUE TITLE
AccessDeniedException for Lambda Layers

### ISSUE THREAD

**Issue by radimsuckr** [DataDog/datadog-lambda-layer-python#39]
## Expected Behavior
Python 3.8 Layer of version 11 works in eu-central-1 region.

## Actual Behavior
I simply copied Layer ARN and replaced the variable parts so it looks like this `arn:aws:lambda:${var.region}:464622532012:layer:Datadog-Python38:11` however i keep getting AccessDeniedException in Terraform.

```
* aws_lambda_function.datadog-lambda: Error modifying Lambda Function Configuration <redacted>: AccessDeniedException: User: arn:aws:sts::<redacted>:<redacted> is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Python38:11
```

## Steps to Reproduce the Problem

  1. Change Lambda Layer so it uses Python 3.8, Layer version 11 and is in eu-central-1

## Specifications

  - Datadog Lambda Layer version: 11
  - Python version: 3.8
  
## Stacktrace
None.

**Comment by tianchu** [comment]
Hi @radimsuckr, unfortunately I cannot reproduce this issue. I was able to add the layer `arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Python38:11` to my testing Lambda function in a testing AWS account without problem. I suspect it's an issue either with terraform or the IAM role used? Can you try manually (via the Lambda console) add this layer to a testing Lambda function in your AWS account, and see if that works?

**Comment by radimsuckr** [comment]
@tianchu When I changed the layers manually everything went fine. However I still have the issue in Terraform and it's weird because it works just fine for Python 2.7 and following layers:
```
"arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Python27:3"
"arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Trace-Forwarder-Python27:1"
```
I'd expect to have the very same issue with permissions for these two layers if it would be caused by IAM policies.

**Comment by tianchu** [comment]
Hi @radimsuckr from what I can tell, everything on our side are the same for Python27 and Python38 layers. Based on the error you recieved `User: arn:aws:sts::<redacted>:<redacted> is not authorized to perform: lambda:GetLayerVersion on resource`, can you double check the user being used by Terraform has the `lambda:GetLayerVersion` access to Python38 layers?

**Comment by sfirrin** [comment]
Hey @radimsuckr since this issue has been inactive for a while I'm going to close it out. Feel free to reopen the issue if we can provide more help.

**Comment by jonseymour** [comment]
Having experienced a similar symptom with a different layer, I found that the issue was resolved by ensuring the s3key of the aws_lambda_layer_version resource in the terraform was actually pointing to a zip that existed. For whatever reason, fi that key specifies an non-existant zip the discrepancy is reported as a "AccessDenied" error.

**Comment by bangouraboulaye** [comment]
> Having experienced a similar symptom with a different layer, I found that the issue was resolved by garantierend the s3key of the aws_lambda_layer_version resource in the terraform was actually pointing to a zip that existed. For whatever reason, fi that key specifies an non-existant zip the discrepancy is reported as a "AccessDenied" error

Hi, could you tell me please, how did you solve it?
