### ISSUE TITLE
Links to changelog are dead

### ISSUE THREAD

**Issue by ascandella** [DataDog/datadog-lambda-layer-python#54]
It looks like this was removed in 95b8f01bc9495964cadc5126917ddc54fd716d09

According to readme you are supposed to look at the changelog to figure out what version of the lambda layer to use. I'm assuming this should be updated to look at GitHub releases but want to double check

**Comment by tianchu** [comment]
Thanks for catching this, the link to the removed CHANGELOG has been updated to [github releases](https://github.com/DataDog/datadog-lambda-layer-python/releases)
