### ISSUE TITLE
Misleading Blog Post

### ISSUE THREAD

**Issue by JoeAlamo** [DataDog/datadog-lambda-layer-python#6]
Hey there, apologies if this isn't the right place for this report.

I've been getting lambda metrics set up and was referring to a few different sources of info: this repo, aws lambda integration docs and the blog post here: https://www.datadoghq.com/blog/datadog-lambda-layer/

It seems that blog post is referring to an old lambda layer implementation? For example, importing datadog_lambda_wrapper from datadog instead of from datadog_lambda.wrapper.

This led me down a wrong path and towards errors as I was partly following that post, and partly following this repo + the docs. Of course it's my fault for not realising that earlier, but it was a little confusing.

**Comment by pinkerton** [comment]
Hey Joe, thanks for the feedback. I actually just updated our docs last week (https://docs.datadoghq.com/integrations/amazon_lambda/?tab=python#installing-and-using-the-datadog-layer) to be more explicit about this, and will go update that blog post as well. Sorry that this was confusing - it's a big priority of right now to make this setup process seamless. 

Please reach out if I can help answer any more questions about Datadog!

**Comment by JoeAlamo** [comment]
Awesome, thank you Stephen! Enjoying it so far.
